name: Trigger auto deployment for bagel-cpu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bagel-deployment.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BAGELCPU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BAGELCPU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BAGELCPU_AZURE_SUBSCRIPTION_ID }}
          
      - name: Login to ACR
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ vars.ACR_NAME }}.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push container image
        run: |
          docker build -t ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.AZURE_APP_NAME }}:${{ github.sha }} .
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.AZURE_APP_NAME }}:${{ github.sha }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name bagel-cpu \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --image ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.AZURE_APP_NAME }}:${{ github.sha }}


