name: Trigger auto deployment for bagel-cpu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bagel-cpu-AutoDeployTrigger-adb7023e-09ec-4255-9655-f2178fae253c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BAGELCPU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BAGELCPU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BAGELCPU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.BAGELCPU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BAGELCPU_REGISTRY_PASSWORD }}
          containerAppName: bagel-cpu
          resourceGroup: ai-framework
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


